# Generated by Django 4.0.4 on 2022-05-06 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=75)),
                ('idade', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('crm', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=30)),
                ('publicado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autualizacao_criacao', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='home/covers/%Y/%m/%d/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.categoria')),
            ],
        ),
    ]
