# Generated by Django 4.0.4 on 2022-05-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='autualizacao_criacao',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_criacao',
        ),
    ]
