# Generated by Django 4.0.4 on 2022-05-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_medico_autualizacao_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=75)),
                ('idade', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=9)),
                ('data', models.DateField()),
            ],
        ),
    ]
