# Generated by Django 4.0.4 on 2022-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_remove_paciente_data_paciente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
